title: Default Page

icon: 📄

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: blocks
            fieldsets:
              - heading
              - text
              - message
              - quote
              - table
              - table-contact
              - markdown
              - code
              - list
              - line
              - image
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files
        template: image
