title:
  en: Site
  de: Webseite
description:
  en: desc
  de: Beschreibung

options:
  update:
    admin: true
    editor: false
  delete:
    admin: true
    editor: false

columns:
  - width: 2/3
    sections:
      stats:
        headline:
          en: Stats
          de: Statistik
        type: stats
        size: small
        reports:
          - label:
              de: Notizen
              en: Notes
            value: "{{ site.pages.find('notes', 'notes.link').children.count }}"
            icon: book
          - label:
              de: Shorts
              en: Shorts
            value: "{{ site.pages.find('shorts').children.count }}"
            icon: megaphone
          - label:
              de: Seiten
              en: Pages
            value: "{{ site.children.count }}"
            icon: page
      drafts: sections/drafts
      notes: sections/notes
  - width: 1/3
    sections:
      pages:
        type: pages
        headline:
          en: Pages
          de: Seiten
        templates:
          - default
          - colophon
          - legal
          - error
        layout: list
        sortable: true
        sortBy: title
  - width: 2/3
    sections:
      shorts: sections/shorts
  - width: 1/3
    sections:
      files: sections/files
  - width: 1/1
    fields:
      socials:
        label:
          en: Social media accounts
          de: Social Media Accounts
        type: structure
        columns:
          platform:
            width: 1/2
          link:
            width: 1/2
        fields:
          platform:
            label:
              en: Platform
              de: Plattform
            type: text
            required: true
          link:
            label:
              en: Link
              de: Link
            type: url
            required: true
